version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: kaliguys
      POSTGRES_PASSWORD: GuysPostgres@12
      ECOMMERICIAL_DATABASE_APPNAME: GuysPostgres@12
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
    - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      args:
        - APP_USER_UID=${APP_USER_UID}
        - APP_GROUP_GID=${APP_GROUP_GID}
    command: bundle exec rails s webrick -b '0.0.0.0'
    environment:
      POSTGRES_USER: kaliguys
      POSTGRES_PASSWORD: GuysPostgres@12
      ECOMMERICIAL_DATABASE_APPNAME: GuysPostgres@12
      PGHOST: db
      PGUSER: kaliguys
      WEBPACKER_DEV_SERVER_HOST: webpack
    volumes:
      - .:/rails-app-docker
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpack
    tty: true
    stdin_open: true
  webpack:
    build: .
    environment:
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: ./bin/webpack-dev-server --hot --inline true
    volumes:
      - .:/rails-app-docker
    ports:
      - '3035:3035'
volumes:
  pgdata: